---
title: "AoA-prediction-plots"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(dplyr.summarise.inform = FALSE)

library(tidyverse)
library(widyr)
#install.packages("widyr")
library(ggthemes)
#library(devtools)
#install_github("langcog/langcog")
library(ggstance)
library(langcog)
library(ggdendro)
library(ggplot2)#
#library(glue)
library(cowplot)
library(ggpubr)
library(sjPlot)

walk(list.files("scripts", pattern = "*.R$", full.names = TRUE), source)
```


## APPROACH 2

```{r lstm}

data <- readRDS("./experiment-results/approach2-results/exp2_all_lexcat_betas_resid_lstm.rds")
data <- data %>% rbind(filter(readRDS("./experiment-results/approach2-results/exp2_all_lexcat_betas_resid_2gm.rds"), term != "unigram"))
data <- data %>% rbind(filter(readRDS("./experiment-results/approach2-results/exp2_all_lexcat_betas_resid_3gm.rds"), term != "unigram"))
data <- data %>% rbind(filter(readRDS("./experiment-results/approach2-results/exp2_all_lexcat_betas_resid_4gm.rds"), term != "unigram"))
data$term = factor(dplyr::recode(data$term, "unigram" = "uni-gram","lstmresid" = "LSTM residual", "2gmresid" = "bi-gram residual", "3gmresid"="tri-gram residual", "4gmresid" = "four-gram residual"), levels = c("LSTM residual", "four-gram residual", "tri-gram residual", "bi-gram residual","uni-gram"))
data <- data |> filter(term != "concreteness")


lex.labs <- c("function words", "nouns", "predicates")
names(lex.labs) <- c("fctwd", "noun", "pred")

make_lang_plot <- function(lang){
  lang_data <- data |> filter(language == lang)
  p = ggplot(lang_data, aes(x = estimate, y = term, colour = term, fill=term)) +
  facet_grid(~ lexical_category, labeller = labeller(lexical_category = lex.labs)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  geom_point(alpha=0.4, position = position_jitter(w = 0, h = 0.1), show.legend = FALSE)+
  labs(x = "Surprisal estimate", y = "") +
  theme_bw() +
  theme(text=element_text(size=12,  family="Times New Roman"), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 12),
        plot.margin = margin(1, 0.5, 0.5, 0.1, "cm"))
  return(p)
}

p_EnAm = make_lang_plot("English (American)")
p_EnBr = make_lang_plot("English (British)")
p_EnAu = make_lang_plot("English (Australian)")
p_Gr = make_lang_plot("German")
p_FrEu = make_lang_plot("French (French)")
p_FrQc = make_lang_plot("French (Quebecois)")
p_SpEu = make_lang_plot("Spanish (European)")
p_SpMx = make_lang_plot("Spanish (Mexican)")
p_MaBj = make_lang_plot("Mandarin (Beijing)")
p_MaTw = make_lang_plot("Mandarin (Taiwanese)")

p_EnAm

plots_exp2 = ggarrange(p_EnAm+rremove("xlab"), p_EnBr+rremove("xlab")+rremove("y.text"), p_EnAu+rremove("xlab"), p_Gr+rremove("xlab")+rremove("y.text"), p_FrEu+rremove("xlab"), 
                       p_FrQc+rremove("xlab")+rremove("y.text"), p_SpEu+rremove("xlab"), p_SpMx+rremove("xlab")+rremove("y.text"), p_MaBj, p_MaTw+rremove("y.text"),
          labels = c("English (American)", "English (British)", "English (Australian)", "German", "French (European)",
                     "French (Quebecois)", "Spanish (European)", "Spanish (Mexican)", "Mandarin (Beijingese)", "Mandarin (Taiwanese)"),
          ncol = 2, nrow = 5,
          font.label = list(size = 12, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4), widths = c(1, .8))

ggsave("plots_approach2_betas_resid.jpeg",plot=plots_exp2, width = 12, height = 12, units="in", limitsize = FALSE)
```

Estimate by lexical category figure by language

```{r lstm}
library(lmSupport)
data <- readRDS("./experiment-results/approach2-results/exp2_all_lexcat_betas_resid_lstm.rds")
data <- data |> filter(term != "concreteness")
data$term <- varRecode(data$term, c("unigram","lstmresid"), c("1gm", "lstm-rd"))


lex.labs <- c("function words", "nouns", "predicates")
names(lex.labs) <- c("fctwd", "noun", "pred")

make_lang_plot <- function(lang){
  lang_data <- data |> filter(language == lang)
  p = ggplot(lang_data, aes(x = estimate, y = term, colour = term, fill=term)) +
  facet_grid(~ lexical_category, labeller = labeller(lexical_category = lex.labs)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  geom_point(alpha=0.3, position = position_jitter(w = 0, h = 0.1), show.legend = FALSE)+
  labs(x = "Surprisal estimate", y = "") +
  theme_bw() +
  theme(text=element_text(size=12,  family="Times New Roman"), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 12),
        plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))
  return(p)
}

p_EnAm = make_lang_plot("English (American)")
p_EnBr = make_lang_plot("English (British)")
p_EnAu = make_lang_plot("English (Australian)")
p_Gr = make_lang_plot("German")
p_FrEu = make_lang_plot("French (French)")
p_FrQc = make_lang_plot("French (Quebecois)")
p_SpEu = make_lang_plot("Spanish (European)")
p_SpMx = make_lang_plot("Spanish (Mexican)")
p_MaBj = make_lang_plot("Mandarin (Beijing)")
p_MaTw = make_lang_plot("Mandarin (Taiwanese)")


plots_exp2 = ggarrange(p_EnAm+rremove("xlab"), p_EnBr+rremove("xlab"), p_EnAu+rremove("xlab"), p_Gr+rremove("xlab"), p_FrEu+rremove("xlab"), 
                       p_FrQc+rremove("xlab"), p_SpEu+rremove("xlab"), p_SpMx+rremove("xlab"), p_MaBj, p_MaTw,
          labels = c("English (American)", "English (British)", "English (Australian)", "German", "French (European)",
                     "French (Quebecois)", "Spanish (European)", "Spanish (Mexican)", "Mandarin (Beijingese)", "Mandarin (Taiwanese)"),
          ncol = 2, nrow = 5,
          font.label = list(size = 12, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4))

ggsave("plots_exp3_betas_resid_lstm_2.jpeg",plot=plots_exp2, width = 12, height = 10, units="in", limitsize = FALSE)
```

```{r 2gm}
library(lmSupport)
data <- readRDS("./experiment-results/diss/exp2_all_lexcat_betas_resid_2gm.rds")
data <- data |> filter(term != "concreteness")
data$term <- varRecode(data$term, c("unigram","2gmresid"), c("1gm", "2gm-rd"))


lex.labs <- c("function words", "nouns", "predicates")
names(lex.labs) <- c("fctwd", "noun", "pred")

make_lang_plot <- function(lang){
  lang_data <- data |> filter(language == lang)
  p = ggplot(lang_data, aes(x = estimate, y = term, colour = term, fill=term)) +
  facet_grid(~ lexical_category, labeller = labeller(lexical_category = lex.labs)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  geom_point(alpha=0.3, position = position_jitter(w = 0, h = 0.1), show.legend = FALSE)+
  labs(x = "Surprisal estimate", y = "") +
  theme_bw() +
  theme(text=element_text(size=12,  family="Times New Roman"), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 12),
        plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))
  return(p)
}

p_EnAm = make_lang_plot("English (American)")
p_EnBr = make_lang_plot("English (British)")
p_EnAu = make_lang_plot("English (Australian)")
p_Gr = make_lang_plot("German")
p_FrEu = make_lang_plot("French (French)")
p_FrQc = make_lang_plot("French (Quebecois)")
p_SpEu = make_lang_plot("Spanish (European)")
p_SpMx = make_lang_plot("Spanish (Mexican)")
p_MaBj = make_lang_plot("Mandarin (Beijing)")
p_MaTw = make_lang_plot("Mandarin (Taiwanese)")


plots_exp2 = ggarrange(p_EnAm+rremove("xlab"), p_EnBr+rremove("xlab"), p_EnAu+rremove("xlab"), p_Gr+rremove("xlab"), p_FrEu+rremove("xlab"), 
                       p_FrQc+rremove("xlab"), p_SpEu+rremove("xlab"), p_SpMx+rremove("xlab"), p_MaBj, p_MaTw,
          labels = c("English (American)", "English (British)", "English (Australian)", "German", "French (European)",
                     "French (Quebecois)", "Spanish (European)", "Spanish (Mexican)", "Mandarin (Beijingese)", "Mandarin (Taiwanese)"),
          ncol = 2, nrow = 5,
          font.label = list(size = 12, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4))

ggsave("plots_exp3_betas_resid_2gm_2.jpeg",plot=plots_exp2, width = 12, height = 10, units="in", limitsize = FALSE)
```

```{r 3gm}
library(lmSupport)
data <- readRDS("./experiment-results/diss/exp2_all_lexcat_betas_resid_3gm.rds")
data <- data |> filter(term != "concreteness")
data$term <- varRecode(data$term, c("unigram","3gmresid"), c("1gm", "3gm-rd"))


lex.labs <- c("function words", "nouns", "predicates")
names(lex.labs) <- c("fctwd", "noun", "pred")

make_lang_plot <- function(lang){
  lang_data <- data |> filter(language == lang)
  p = ggplot(lang_data, aes(x = estimate, y = term, colour = term, fill=term)) +
  facet_grid(~ lexical_category, labeller = labeller(lexical_category = lex.labs)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  geom_point(alpha=0.3, position = position_jitter(w = 0, h = 0.1), show.legend = FALSE)+
  labs(x = "Surprisal estimate", y = "") +
  theme_bw() +
  theme(text=element_text(size=12,  family="Times New Roman"), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 12),
        plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))
  return(p)
}

p_EnAm = make_lang_plot("English (American)")
p_EnBr = make_lang_plot("English (British)")
p_EnAu = make_lang_plot("English (Australian)")
p_Gr = make_lang_plot("German")
p_FrEu = make_lang_plot("French (French)")
p_FrQc = make_lang_plot("French (Quebecois)")
p_SpEu = make_lang_plot("Spanish (European)")
p_SpMx = make_lang_plot("Spanish (Mexican)")
p_MaBj = make_lang_plot("Mandarin (Beijing)")
p_MaTw = make_lang_plot("Mandarin (Taiwanese)")


plots_exp2 = ggarrange(p_EnAm+rremove("xlab"), p_EnBr+rremove("xlab"), p_EnAu+rremove("xlab"), p_Gr+rremove("xlab"), p_FrEu+rremove("xlab"), 
                       p_FrQc+rremove("xlab"), p_SpEu+rremove("xlab"), p_SpMx+rremove("xlab"), p_MaBj, p_MaTw,
          labels = c("English (American)", "English (British)", "English (Australian)", "German", "French (European)",
                     "French (Quebecois)", "Spanish (European)", "Spanish (Mexican)", "Mandarin (Beijingese)", "Mandarin (Taiwanese)"),
          ncol = 2, nrow = 5,
          font.label = list(size = 12, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4))

ggsave("plots_exp3_betas_resid_3gm_2.jpeg",plot=plots_exp2, width = 12, height = 10, units="in", limitsize = FALSE)
```

```{r 4gm}
library(lmSupport)
data <- readRDS("./experiment-results/diss/exp2_all_lexcat_betas_resid_4gm.rds")
data <- data |> filter(term != "concreteness")
data$term <- varRecode(data$term, c("unigram","4gmresid"), c("1gm", "4gm-rd"))


lex.labs <- c("function words", "nouns", "predicates")
names(lex.labs) <- c("fctwd", "noun", "pred")

make_lang_plot <- function(lang){
  lang_data <- data |> filter(language == lang)
  p = ggplot(lang_data, aes(x = estimate, y = term, colour = term, fill=term)) +
  facet_grid(~ lexical_category, labeller = labeller(lexical_category = lex.labs)) +
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  geom_point(alpha=0.3, position = position_jitter(w = 0, h = 0.1), show.legend = FALSE)+
  labs(x = "Surprisal estimate", y = "") +
  theme_bw() +
  theme(text=element_text(size=12,  family="Times New Roman"), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), strip.text.x = element_text(size = 12),
        plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))
  return(p)
}

p_EnAm = make_lang_plot("English (American)")
p_EnBr = make_lang_plot("English (British)")
p_EnAu = make_lang_plot("English (Australian)")
p_Gr = make_lang_plot("German")
p_FrEu = make_lang_plot("French (French)")
p_FrQc = make_lang_plot("French (Quebecois)")
p_SpEu = make_lang_plot("Spanish (European)")
p_SpMx = make_lang_plot("Spanish (Mexican)")
p_MaBj = make_lang_plot("Mandarin (Beijing)")
p_MaTw = make_lang_plot("Mandarin (Taiwanese)")


plots_exp3 = ggarrange(p_EnAm+rremove("xlab"), p_EnBr+rremove("xlab"), p_EnAu+rremove("xlab"), p_Gr+rremove("xlab"), p_FrEu+rremove("xlab"), 
                       p_FrQc+rremove("xlab"), p_SpEu+rremove("xlab"), p_SpMx+rremove("xlab"), p_MaBj, p_MaTw,
          labels = c("English (American)", "English (British)", "English (Australian)", "German", "French (European)",
                     "French (Quebecois)", "Spanish (European)", "Spanish (Mexican)", "Mandarin (Beijingese)", "Mandarin (Taiwanese)"),
          ncol = 2, nrow = 5,
          font.label = list(size = 12, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4))

ggsave("plots_exp3_betas_resid_4gm_2.jpeg",plot=plots_exp3, width = 12, height = 10, units="in", limitsize = FALSE)
```


# APPROACH 3


```{r fit_model_random_slope2}
models_random_slope_noun <- readRDS("./data/models_random_slope_noun.rds")
models_random_slope_pred <- readRDS("./data/models_random_slope_pred.rds")

#element_textbox <- function(...) {
#  el <- element_text(...)
#  class(el) <- c("element_textbox", class(el))
#  el
#}

#element_grob.element_textbox <- function(element, ...) {
#  text_grob <- NextMethod()
#  rect_grob <- element_grob(calc_element("strip.background", theme_bw()))
#  
#  ggplot2:::absoluteGrob(
#    grid::gList(
#      element_grob(calc_element("strip.background", theme_bw())),
#      text_grob
#    ),
#    height = grid::grobHeight(text_grob), 
#    width = grid::unit(1, "npc")
#  )
#}


p1 <- models_random_slope_noun[1:4] |> plot_models(p.shape = T,show.legend = T, m.labels = c("residualised LSTM","residualised bi-gram","residualised tri-gram","residualised four-gram"), axis.labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual")) + ylim(-8,2.5) + labs(title = "Nouns")+
  scale_colour_discrete("Models")+
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  theme_bw() +
  theme(legend.position="bottom")+
  theme(plot.title = element_text(hjust = 0.5, margin = margin(t = 5, b = 5), face="bold"), text=element_text(size=20,  family="Times New Roman"), legend.text = element_text(size = 18), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), strip.text.x = element_text(size = 20))

ggsave("p1b_exp4_model_3.jpeg",plot=p1, width = 6, height = 4, units="in", limitsize = FALSE)


p2 <- models_random_slope_pred[1:4] |> plot_models(p.shape = T,show.legend = T, m.labels = c("residualised LSTM","residualised bi-gram","residualised tri-gram","residualised four-gram"), axis.labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual")) + ylim(-8,2.5) + labs(title = "Predicates")  +
  scale_colour_discrete("Models")+
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) +
  theme_bw() +
  theme(legend.position="bottom")+
  theme(plot.title = element_text(hjust = 0.5, margin = margin(t = 5, b = 5), face="bold"), text=element_text(size=20,  family="Times New Roman"), legend.text = element_text(size = 18), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), strip.text.x = element_text(size = 20))

ggsave("p2_exp4_model_3.jpeg",plot=p2, width = 6, height = 4, units="in", limitsize = FALSE)

plots_exp4_1 = ggarrange(p1, p2, 
          #labels = c("Nouns", "Predicates"),
          ncol = 2, nrow = 1,
          font.label = list(size = 15, color = "black", face = "bold", family = "Times New Roman"),
          label.x = c(0.4, 0.4, 0.4, 0.5, 0.4), widths = c(1, 1))
plots_exp4_1

#ggsave("plots_exp4_model_3.jpeg",plot=plots_exp4_1, width = 18, height = 7, units="in", limitsize = FALSE)
#saveRDS(models_random_slope_noun, "./data/models_random_slope_noun.rds")
#saveRDS(models_random_slope_pred, "./data/models_random_slope_pred.rds")
#models_random_slope_noun<-readRDS("./data/models_random_slope_noun.rds")
```

```{r compare_languages_random_effect - no concreteness}
p_lstm_sd <- coef(models_random_slope_pred$lstm_surp_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "predicates") |> 
  rbind(coef(models_random_slope_noun$lstm_surp_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "nouns")) |> 
  filter(preds != "concreteness") |>
  ggplot(aes(x = estimates, y = preds, color = language)) + 
  geom_point(size = 3, alpha=0.7, position = position_jitter(w = 0, h = 0.1)) + 
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) + 
  facet_grid(~lexical_category) +
  scale_y_discrete(labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual"))+
  scale_color_discrete(labels=c("French (French)"= "French (European)", "Mandarin (Beijing)" = "Mandarin (Beijingese)" ))+
  labs(x = "Coefficient estimate", y = "") + 
  ggtitle("Residualised LSTM surprisal") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, face="bold"), legend.title = element_blank(), text=element_text(size=15,  family="Times New Roman"), axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15), strip.text.x = element_text(size = 15), plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))

ggsave("approach3_lstm_languages.jpeg",plot=p_lstm_sd, width = 12, height = 4, units="in", limitsize = FALSE)

```

```{r}
p_2gm_sd <- coef(models_random_slope_pred$surp_2gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "predicates") |> 
  rbind(coef(models_random_slope_noun$surp_2gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "nouns")) |> 
  filter(preds != "concreteness") |>
  ggplot(aes(x = estimates, y = preds, color = language)) + 
  geom_point(size = 3, alpha=0.7, position = position_jitter(w = 0, h = 0.1)) + 
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) + 
  facet_grid(~lexical_category) +
  scale_y_discrete(labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual"))+
  labs(x = "Coefficient estimate", y = "") + 
  labs(x = "Coefficient estimate", y = "") + 
  ggtitle("Residualized bi-gram surprisal") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, face="bold"), legend.title = element_blank(), legend.position="none", text=element_text(size=15,  family="Times New Roman"), axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15), strip.text.x = element_text(size = 15), plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))

p_3gm_sd <- coef(models_random_slope_pred$surp_3gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "predicates") |> 
  rbind(coef(models_random_slope_noun$surp_3gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "nouns")) |> 
  filter(preds != "concreteness") |>
  ggplot(aes(x = estimates, y = preds, color = language)) + 
  geom_point(size = 3, alpha=0.7, position = position_jitter(w = 0, h = 0.1)) + 
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) + 
  facet_grid(~lexical_category) +
  scale_y_discrete(labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual"))+
  labs(x = "Coefficient estimate", y = "") + 
  labs(x = "Coefficient estimate", y = "") + 
  ggtitle("Residualized tri-gram surprisal") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, face="bold"), legend.title = element_blank(), legend.position="none", text=element_text(size=15,  family="Times New Roman"), axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15), strip.text.x = element_text(size = 15), plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))

p_4gm_sd <- coef(models_random_slope_pred$surp_4gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "predicates") |> 
  rbind(coef(models_random_slope_noun$surp_4gm_rd)$language |> rownames_to_column(var = "language") |> rename(Intercept = "(Intercept)") |> gather(preds, estimates, 3:5) |> mutate(lexical_category = "nouns")) |> 
  filter(preds != "concreteness") |>
  ggplot(aes(x = estimates, y = preds, color = language)) + 
  geom_point(size = 3, alpha=0.7, position = position_jitter(w = 0, h = 0.1)) + 
  geom_vline(xintercept = 0, color = "grey", linetype = "dotted", size = 1) + 
  facet_grid(~lexical_category) +
  scale_y_discrete(labels=c("concreteness" = "concreteness", "surprisal_1gm" = "uni-gram","lstm_surp_resid" = "LSTM residual", "surp_2gm_resid" = "bi-gram residual", "surp_3gm_resid"="tri-gram residual", "surp_4gm_resid" = "four-gram residual"))+
    scale_color_discrete(labels=c("French (French)"= "French (European)", "Mandarin (Beijing)" = "Mandarin (Beijingese)" ))+
  labs(x = "Coefficient estimate", y = "") + 
  labs(x = "Coefficient estimate", y = "") + 
  ggtitle("Residualized four-gram surprisal") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, face="bold"), legend.title = element_blank(), legend.position="bottom", text=element_text(size=15,  family="Times New Roman"), axis.text.x = element_text(size = 15), axis.text.y = element_text(size = 15), strip.text.x = element_text(size = 15), plot.margin = margin(1, 0.5, 0.5, 0.5, "cm"))


plots_exp4 = ggarrange(p_2gm_sd+rremove("xlab"), p_3gm_sd+rremove("xlab"), p_4gm_sd, 
          #labels = c("Residualized LSTM surprisal", "Residualized bi-gram surprisal", "Residualized tri-gram surprisal", "Residualized four-gram surprisal"),
          #hjust = 0.5,
          ncol = 1,
          font.label = list(size = 15, color = "black", face = "bold", family = "Times New Roman"), heights = c(.72, .72, 1))

plots_exp4

ggsave("approach3_ngrams_languages.jpeg",plot=plots_exp4, width = 12, height = 10, units="in", limitsize = FALSE)
```