---
title: "merge_surprisal_childes"
author: "Yuguang Duan"
date: "12/10/2021"
output: html_document
---

```{r}
library(car)
library(ggplot2)
library(lmSupport)
library(psych)
library(purrr)
library(stringr)
library(tidyverse)
```

```{r}
childes <- read.csv("word_list_cleaned/word_list_mandarin_(beijing)_clean.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_zh_2gm_surprisal.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_zh_3gm_surprisal.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_zh_4gm_surprisal.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_zh_5gm_surprisal.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_zh_6gm_surprisal.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_mandarin_(beijing)_cleaned_surprisal.csv",  row.names = FALSE)
```

```{r}
childes <- read.csv("word_list_cleaned/word_list_mandarin_(taiwanese)_clean.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_zh_2gm_surprisal.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_zh_3gm_surprisal.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_zh_4gm_surprisal.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_zh_5gm_surprisal.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_zh_6gm_surprisal.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_mandarin_(taiwanese)_cleaned_surprisal.csv",  row.names = FALSE)
```

```{r}
childes <- read.csv("word_list_cleaned/word_list_german_clean_caps.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_de_2gm_surprisal_caps.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_de_3gm_surprisal_caps.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_de_4gm_surprisal_caps.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_de_5gm_surprisal_caps.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_de_6gm_surprisal_caps.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_german_cleaned_surprisal.csv",  row.names = FALSE)
```

```{r}
childes <- read.csv("word_list_cleaned/word_list_english_(american)_clean.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_en_2gm_surprisal.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_en_3gm_surprisal.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_en_4gm_surprisal.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_en_5gm_surprisal.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_en_6gm_surprisal.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_english_(american)_cleaned_surprisal.csv",  row.names = FALSE)

childes <- read.csv("word_list_cleaned/word_list_english_(australian)_clean.csv")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_english_(australian)_cleaned_surprisal.csv",  row.names = FALSE)

childes <- read.csv("word_list_cleaned/word_list_english_(british)_clean.csv")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_english_(british)_cleaned_surprisal.csv",  row.names = FALSE)
```

```{r}
childes <- read.csv("word_list_cleaned/word_list_french_(french)_clean.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_fr_2gm_surprisal.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_fr_3gm_surprisal.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_fr_4gm_surprisal.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_fr_5gm_surprisal.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_fr_6gm_surprisal.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_french_(french)_cleaned_surprisal.csv",  row.names = FALSE)
childes <- read.csv("word_list_cleaned/word_list_french_(quebecois)_clean.csv")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_french_(quebecois)_cleaned_surprisal.csv",  row.names = FALSE)
```


```{r}
childes <- read.csv("word_list_cleaned/word_list_spanish_(european)_clean.csv")
childes_surprisal2gm <- read.csv("surprisal/childes_es_2gm_surprisal.txt")
childes_surprisal3gm <- read.csv("surprisal/childes_es_3gm_surprisal.txt")
childes_surprisal4gm <- read.csv("surprisal/childes_es_4gm_surprisal.txt")
childes_surprisal5gm <- read.csv("surprisal/childes_es_5gm_surprisal.txt")
childes_surprisal6gm <- read.csv("surprisal/childes_es_6gm_surprisal.txt")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_spanish_(european)_cleaned_surprisal.csv",  row.names = FALSE)
childes <- read.csv("word_list_cleaned/word_list_spanish_(mexican)_clean.csv")
childes_surp <- childes %>% merge(childes_surprisal2gm%>%rename(word_clean = word,surprisal_2gm = info_float) %>% mutate(sum_cnt = sum(cnt), frequency = -log(cnt/sum_cnt))%>%select(word_clean,cnt,frequency,surprisal_2gm),all.x = TRUE) %>% merge(childes_surprisal3gm%>%rename(word_clean = word,surprisal_3gm = info_float)%>%select(word_clean,surprisal_3gm),all.x = TRUE) %>% merge(childes_surprisal4gm%>%rename(word_clean = word,surprisal_4gm = info_float)%>%select(word_clean,surprisal_4gm),all.x = TRUE) %>% merge(childes_surprisal5gm%>%rename(word_clean = word,surprisal_5gm = info_float)%>%select(word_clean,surprisal_5gm),all.x = TRUE) %>% merge(childes_surprisal6gm%>%rename(word_clean = word,surprisal_6gm = info_float)%>%select(word_clean,surprisal_6gm),all.x = TRUE)
corr.test(childes_surp %>% select(surprisal_2gm,surprisal_3gm,surprisal_4gm,surprisal_5gm,surprisal_6gm))
childes_surp %>% write.csv(file = "ngram_childes_surprisal/word_list_spanish_(mexican)_cleaned_surprisal.csv",  row.names = FALSE)

```


